# Generated by Django 6.0.3 on 2026-03-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Course Title')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('professor', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
